export default {
  v: '5.3.1',
  fr: 60,
  ip: 0,
  op: 30,
  w: 72,
  h: 72,
  nm: 'menu_animate',
  ddd: 0,
  assets: [
    {
      id: 'comp_0',
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 4,
          nm: 'top',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, n: ['0p667_1_0p333_0'], t: 0, s: [0], e: [45] },
                { t: 30 },
              ],
              ix: 10,
            },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.5, y: 1 },
                  o: { x: 0.5, y: 0 },
                  n: '0p5_1_0p5_0',
                  t: 0,
                  s: [9, 22.5, 0],
                  e: [15.317, 18.499, 0],
                  to: [1.05285441875458, -0.66681545972824, 0],
                  ti: [-1.05285441875458, 0.66681545972824, 0],
                },
                { t: 30 },
              ],
              ix: 2,
            },
            a: { a: 0, k: [-27, 2.25, 0], ix: 1 },
            s: { a: 0, k: [100, 100, 100], ix: 6 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [[0, 0], [0, 0], [0, 0], [0, 0]],
                      o: [[0, 0], [0, 0], [0, 0], [0, 0]],
                      v: [[-9, -0.75], [-9, 0.75], [9, 0.75], [9, -0.75]],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'rd',
                  nm: 'Round Corners 1',
                  r: { a: 0, k: 0.75, ix: 1 },
                  ix: 2,
                  mn: 'ADBE Vector Filter - RC',
                  hd: false,
                },
                {
                  ty: 'fl',
                  c: { a: 0, k: [0.20000000298, 0.20000000298, 0.20000000298, 1], ix: 4 },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  nm: 'Fill 1',
                  mn: 'ADBE Vector Graphic - Fill',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [300, 300], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'top',
              np: 3,
              cix: 2,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
          ],
          ip: 0,
          op: 60,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 4,
          nm: 'mid',
          sr: 1,
          ks: {
            o: {
              a: 1,
              k: [
                {
                  i: { x: [0.833], y: [0.833] },
                  o: { x: [0.167], y: [0.167] },
                  n: ['0p833_0p833_0p167_0p167'],
                  t: 0,
                  s: [100],
                  e: [0],
                },
                { t: 15 },
              ],
              ix: 11,
            },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [36, 36, 0], ix: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [100, 100, 100], ix: 6 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [[0, 0], [0, 0], [0, 0], [0, 0]],
                      o: [[0, 0], [0, 0], [0, 0], [0, 0]],
                      v: [[-9, 0.75], [9, 0.75], [9, -0.75], [-9, -0.75]],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'rd',
                  nm: 'Round Corners 1',
                  r: { a: 0, k: 0.75, ix: 1 },
                  ix: 2,
                  mn: 'ADBE Vector Filter - RC',
                  hd: false,
                },
                {
                  ty: 'fl',
                  c: { a: 0, k: [0.20000000298, 0.20000000298, 0.20000000298, 1], ix: 4 },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  nm: 'Fill 1',
                  mn: 'ADBE Vector Graphic - Fill',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [300, 300], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'mid 1',
              np: 3,
              cix: 2,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
          ],
          ip: 0,
          op: 60,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 3,
          ty: 4,
          nm: 'bottom',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [0] },
                  n: ['0p667_1_0p333_0'],
                  t: 0,
                  s: [0],
                  e: [-45],
                },
                { t: 30 },
              ],
              ix: 10,
            },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.5, y: 1 },
                  o: { x: 0.5, y: 0 },
                  n: '0p5_1_0p5_0',
                  t: 0,
                  s: [9, 49.5, 0],
                  e: [15.317, 53.501, 0],
                  to: [1.05285441875458, 0.66681545972824, 0],
                  ti: [-1.05285441875458, -0.66681545972824, 0],
                },
                { t: 30 },
              ],
              ix: 2,
            },
            a: { a: 0, k: [-27, -2.25, 0], ix: 1 },
            s: { a: 0, k: [100, 100, 100], ix: 6 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  ind: 0,
                  ty: 'sh',
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [[0, 0], [0, 0], [0, 0], [0, 0]],
                      o: [[0, 0], [0, 0], [0, 0], [0, 0]],
                      v: [[-9, 0.75], [9, 0.75], [9, -0.75], [-9, -0.75]],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: 'Path 1',
                  mn: 'ADBE Vector Shape - Group',
                  hd: false,
                },
                {
                  ty: 'rd',
                  nm: 'Round Corners 1',
                  r: { a: 0, k: 0.75, ix: 1 },
                  ix: 2,
                  mn: 'ADBE Vector Filter - RC',
                  hd: false,
                },
                {
                  ty: 'fl',
                  c: { a: 0, k: [0.20000000298, 0.20000000298, 0.20000000298, 1], ix: 4 },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  nm: 'Fill 1',
                  mn: 'ADBE Vector Graphic - Fill',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [300, 300], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'bottom',
              np: 3,
              cix: 2,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
          ],
          ip: 0,
          op: 60,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 4,
          ty: 4,
          nm: 'bounds',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [36, 36, 0], ix: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [100, 100, 100], ix: 6 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  ty: 'rc',
                  d: 1,
                  s: { a: 0, k: [24, 24], ix: 2 },
                  p: { a: 0, k: [0, 0], ix: 3 },
                  r: { a: 0, k: 0, ix: 4 },
                  nm: 'Rectangle Path 1',
                  mn: 'ADBE Vector Shape - Rect',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [300, 300], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transform',
                },
              ],
              nm: 'bounds',
              np: 1,
              cix: 2,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
          ],
          ip: 0,
          op: 60,
          st: 0,
          bm: 0,
        },
      ],
    },
  ],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 0,
      nm: 'Pre-comp 1',
      refId: 'comp_0',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: {
          a: 1,
          k: [
            { i: { x: [0.667], y: [1] }, o: { x: [0.5], y: [0] }, n: ['0p667_1_0p5_0'], t: 0, s: [0], e: [180] },
            { t: 30 },
          ],
          ix: 10,
        },
        p: { a: 0, k: [36, 36, 0], ix: 2 },
        a: { a: 0, k: [36, 36, 0], ix: 1 },
        s: { a: 0, k: [100, 100, 100], ix: 6 },
      },
      ao: 0,
      w: 72,
      h: 72,
      ip: 0,
      op: 60,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
};
